### ISSUE TITLE
Feature: Add wiki-style 'show history' button to pages

### ISSUE THREAD

**Issue by MasssiveJuice08** [morrowind-modding/morrowind-modding.github.io#54]
## About:

Wikipedia and other Mediawiki sites have a 'show history' button on articles and multimedia files, linking to the file revision history of the page or media.

MMW has this indirectly through its use of Github, though locating said file means digging through the Github repo to find the file corresponding to the webpage you're wanting to view the history for – bit of extra legwork.

## Proposed Feature:

Create a component which adds a **'show history'** button to `beforeContent` in every page. The link destination would correspond to the Github file history for the relevant file.

**Comment by MasssiveJuice08** [comment]
Found someone has added both a 'show history' and an 'edit page' button to their own Quartz here! https://github.com/jackyzha0/quartz/issues/710

**Comment by magicaldave** [comment]
Closed by 33704ed
